apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "15.1.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    serverFiles:
      prometheus.yml:
        scrape_configs:
          - job_name: kong-prometheus
            static_configs:
              - targets:
                - kong-metrics.kong:8100